name: NWChem-wiki.mirroring
on:
  push:
  release:
  schedule:
    - cron: '0 0 * * *'
  repository_dispatch:
    types: [backend_automation]
  workflow_dispatch:
jobs:
  mirror_dotwiki2repo:
    if: |
      github.event_name == 'schedule' ||
      (!contains(github.event.head_commit.message, 'ci skip'))
    runs-on: [ubuntu-18.04]
    steps:
      - name: Checkout nwchem-wiki
        uses: actions/checkout@v2
        with:
          repository: nwchemgit/nwchem-wiki
          persist-credentials: false
          fetch-depth: 0
      - name: fetch and merge
        run: |
          git config user.name "nwchemgit"
          git config user.email "nwchemgit@gmail.com"
          git config pull.rebase false
          git remote add upstream https://github.com/nwchemgit/nwchem.wiki > /dev/null 2>&1
          git fetch origin
          git fetch upstream
          git merge upstream/master --no-edit
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
            
  mirror_repo2dotwiki:
    if: |
      github.event_name == 'schedule' ||
      (!contains(github.event.head_commit.message, 'ci skip'))
    needs: mirror_dotwiki2repo
    runs-on: [ubuntu-18.04]
    steps:
      - name: Checkout nwchem.wiki
        uses: actions/checkout@v2
        with:
          repository: nwchemgit/nwchem.wiki
          persist-credentials: false
          fetch-depth: 0
      - name: fetch and merge
        run: |
          git config user.name "nwchemgit"
          git config user.email "nwchemgit@gmail.com"
          git config pull.rebase false
          git remote add upstream https://github.com/nwchemgit/nwchem-wiki > /dev/null 2>&1
          git fetch origin
          git fetch upstream
          git merge upstream/master --no-edit
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.REPOSITORY_TOKEN }}
          branch: ${{ github.ref }}
          repository: nwchemgit/nwchem.wiki

