name: NWChem-website.update
on:
  release:
  schedule:
    - cron: '0 0 * * *'
  repository_dispatch:
    types: [backend_automation]
  workflow_dispatch:

jobs:
  build-deploy:
    name: Build and deploy docs

    runs-on: ubuntu-latest

    steps:
      - name: checkout wiki
        uses: actions/checkout@v2
        with:
          repository: nwchemgit/nwchem-wiki
          persist-credentials: false
          fetch-depth: 1
      - name: move wiki source under docs
        shell: bash
        working-directory: ../
        run: |
          pwd
          ls -l
          mv nwchem-wiki docs
          mkdir -p nwchem-wiki/mkdocs
          mv docs nwchem-wiki/mkdocs/.
      - name: Checkout mkdocs from the nwchem repository
        shell: bash
        run: |
          env|egrep GITHU
          env|egrep runner
          cd $GITHUB_WORKSPACE
          cd ..
          ls -lart
          git clone -b $GITHUB_REF_NAME --depth 1  --filter=blob:none --sparse \
          https://github.com/nwchemgit/nwchem nwchem
          cd nwchem
          git sparse-checkout set contrib/mkdocs
          pwd
          ls -lrta
          mv contrib/mkdocs/* $GITHUB_WORKSPACE/mkdocs/.
      - name: check mkdocs directory
        shell: bash
        run: |
          pwd
          ls -lart
          ls -lart mkdocs
          ls -lart mkdocs/docs
      - name: Set up Python 3
        uses: actions/setup-python@v2
      
      - name: install mkdocs and plugins
        shell: bash
        working-directory: mkdocs
        run: |
          pwd
          bash ./install_mkdocs.sh
          mkdocs -h || true
      - name: checkout archived forum
        uses: actions/checkout@v2
        with:
          repository: nwchemgit/archivedforum
          persist-credentials: false
          fetch-depth: 1
      - name: move archiveforum source
        shell: bash
        working-directory: mkdocs/docs/
        run: |
          echo ' ### ls on $GITHUB_WORKSPACE ###'
          ls -lart $GITHUB_WORKSPACE|tail -2
          echo ' ### ls on $GITHUB_WORKSPACE/archivedforum ###'          
          ls -lrt $GITHUB_WORKSPACE/archivedforum
          mv $GITHUB_WORKSPACE/archivedforum/Special_AWCforum .
      - name: build website
        shell: bash
        working-directory: mkdocs
        run: |
          MKDOCS_SERVE=B bash ./build_website.sh
          ls -lart || true
          ls -lart site/index.html || true
      - name: checkout website
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPOSITORY_TOKEN }}
          path: mkdocs/nwchemgit.github.io
          repository: nwchemgit/nwchemgit.github.io
      - name: update nwchemgit.github.io with new content
        shell: bash
        working-directory: mkdocs
        run: |
          rsync --exclude=.git -a site/* nwchemgit.github.io/.
          ls -lart site/index.html || true
          ls -lart nwchemgit.github.io/index.html || true
          cd nwchemgit.github.io
          git diff --stat
          git log -1
      - name: Commit changes
        shell: bash
        working-directory: mkdocs/nwchemgit.github.io
        run: |
            pwd
            ls -lrt ../
            bash ../commit_changes.sh
#      - name: Push changes
#        uses: ad-m/github-push-action@master
#        with:
#          directory: mkdocs/nwchemgit.github.io
#          github_token: ${{ secrets.REPOSITORY_TOKEN }}
#          branch: ${{ github.ref }}
#          repository: nwchemgit/nwchemgit.github.io
      - name: Check commit result
        shell: bash
        working-directory: mkdocs/nwchemgit.github.io
        run: |
            git log -2
